---
- name: Install Apache
  ansible.builtin.dnf:
    name: httpd
    state: present

- name: Create a simple index.html page
  ansible.builtin.copy:
    content: "<h1>Hello World! This Apache server was deployed via Ansible.</h1>"
    dest: /var/www/html/index.html
    mode: '0644'

- name: Start and enable Apache
  ansible.builtin.service:
    name: httpd
    state: started
    enabled: yes
