---
- name: Start Databse Service
  hosts: "{{ _hosts | default(omit) }}"
  gather_facts: true
  become: true

  tasks:
  
    - name: Database role | Start Service
      ansible.builtin.include_role:
        name: demo.application.database
        tasks_from: start_service.yml

