---
- name: Stop Database Service
  hosts: "{{ _hosts | default(omit) }}"
  gather_facts: true
  become: true

  tasks:

    - name: Database role | Stop Service
      ansible.builtin.include_role:
        name: database
        tasks_from: stop_service.yml
